<a id="create-btn" class="rounded-corners" href="<?php echo $this->url( array('controller' => 'admin', 'action' => 'create'), null, true ) ?>">Створити новину</a>

<table id="news-table">
	<tr>
		<th>ID</th>
		<th>Новина</th>
		<th></th>
		<th></th>
	</tr>
	<?php
	// булева змінна для перемикання між парними/непарними рядками таблиці
	// (для візуального ефекту "зебра")
	$isOdd = true;
	?>
    <?php foreach($this->paginator as $news_item) : ?>
        <tr class="<?php echo $isOdd ? 'odd' : 'even'; $isOdd = !$isOdd; ?>">
            <td>
            	<?php echo $news_item['id']; ?>
            </td>
            <td>
            	<div>
            		<a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'view', 'id' => (int)$news_item['id']), null, true ) ?>"><?php echo $this->escape($news_item['title']) ?></a>
            	</div>

				<small>
	            	<?php echo $this->escape($news_item['date']) ?>,
	            	<?php echo $this->escape($this->categoryName($news_item['category_id'])) ?>
	            </small>
            </td>

            <td>
            	<small>
            		<a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'update', 'id' => (int)$news_item['id']), null, true ) ?>">Редагувати</a>
            	</small>
            </td>

            <td>
            	<small>
            		<a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'delete', 'id' => (int)$news_item['id']), null, true ) ?>">Видалити</a>
            	</small>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<?php
// показуємо посторінкову навігацію
echo $this->paginationControl($this->paginator, 'Sliding', 'paginator.phtml');
?>